# Generated by Django 3.0.6 on 2020-05-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0002_auto_20200510_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='amount',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('1', 'Доставлен'), ('2', 'Возвращен'), ('3', 'Выдан')], default='1', max_length=1),
        ),
    ]
