# Generated by Django 3.0.6 on 2020-05-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0004_auto_20200510_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('0', 'Не на складе'), ('1', 'Доставлен'), ('2', 'Возвращен'), ('3', 'Выдан')], default='1', max_length=1),
        ),
    ]
